# This is a config for E2B sandbox template.
# You can use 'template_id' (wxm0wnpbhz13trickv5z) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='wxm0wnpbhz13trickv5z')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'wxm0wnpbhz13trickv5z' })

dockerfile = "e2b.Dockerfile"
template_id = "wxm0wnpbhz13trickv5z"
